app :
  name: Jim
  ver: 1.0.1
  env: local
http:
  host: 0.0.0.0
  port: 9091
  log: log/gin.log

websocket:
  host: 0.0.0.0
  port: 9092
  log: log/websocket.log

rpc:
  host: 127.0.0.1
  port: 9093
  log: log/rpc.log

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  charset: utf8mb4
  database: jim

redis:
  host: 127.0.0.1
  port: 6379
  user: ""
  password: ""
  db: 0

jaeger:
  host: 172.17.0.1 #127.0.0.1
  port: 6831

jwt:
  secret: __jim__

etcd:
  host:
    - 127.0.0.1:2379 #127.0.0.1:2379
  timeout: 6831

pager:
  page_size: 10