// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameDevice = "device"

// Device mapped from table <device>
type Device struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                        // 自增主键
	DeviceID      int64     `gorm:"column:device_id;not null" json:"device_id"`                               // 设备id
	AppID         int64     `gorm:"column:app_id;not null" json:"app_id"`                                     // app_id
	UserID        int64     `gorm:"column:user_id;not null;default:0" json:"user_id"`                         // 账户id
	Type          int32     `gorm:"column:type;not null" json:"type"`                                         // 设备类型,1:Android；2：IOS；3：Windows; 4：MacOS；5：Web
	Brand         string    `gorm:"column:brand;not null" json:"brand"`                                       // 手机厂商
	Model         string    `gorm:"column:model;not null" json:"model"`                                       // 机型
	SystemVersion string    `gorm:"column:system_version;not null" json:"system_version"`                     // 系统版本
	SdkVersion    string    `gorm:"column:sdk_version;not null" json:"sdk_version"`                           // app版本
	Status        int32     `gorm:"column:status;not null;default:0" json:"status"`                           // 在线状态，0：离线；1：在线
	ConnAddr      string    `gorm:"column:conn_addr;not null" json:"conn_addr"`                               // 连接层服务器地址
	ConnFd        int64     `gorm:"column:conn_fd;not null" json:"conn_fd"`                                   // TCP连接对应的文件描述符
	CreateTime    time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	UpdateTime    time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"` // 更新时间
}

// TableName Device's table name
func (*Device) TableName() string {
	return TableNameDevice
}
