// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGroupUser = "group_user"

// GroupUser mapped from table <group_user>
type GroupUser struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`  // 自增主键
	GroupID      int64          `gorm:"column:group_id;not null" json:"group_id"`           // 组id
	UserID       int64          `gorm:"column:user_id;not null" json:"user_id"`             // 用户id
	UserShowname string         `gorm:"column:user_showname;not null" json:"user_showname"` // 用户在群组的昵称
	Extra        string         `gorm:"column:extra;not null" json:"extra"`                 // 附加属性
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`                // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`                // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                // 删除时间
}

// TableName GroupUser's table name
func (*GroupUser) TableName() string {
	return TableNameGroupUser
}
